# Patrick Carra
# make is used to compile binary
# make clean is used to remove all binaries and object files
#
# T1: T1.c
# 	gcc -o T1 T1.c

CC = gcc
CFLAGS = -Wall

proj1: driver.c liblog.h
	$(CC) $(CFLAGS) -o proj1 driver.c liblog.h

clean:
	rm -rf *o  proj1 
