# Patrick Carra
# make is used to compile binary
# make clean is used to remove all binaries and object files
#
# T1: T1.c
# 	gcc -o T1 T1.c

proj1: driver.c liblog.c
	gcc -o proj1 driver.c liblog.c

#liblog: liblog.o
	#ar -rc liblog.a sum.o

clean:
	rm -rf *o  proj1 
