# Patrick Carra
# make is used to compile binary
# make clean is used to remove all binaries and object files

driver: driver.c 
	gcc -o driver driver.c 

#liblog: liblog.o
	#ar -rc liblog.a sum.o

clean:
	rm -f ./*.o 
